[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#20BEFF"
backgroundColor = "#02060D"
secondaryBackgroundColor = "#07121B"
textColor = "#E9FDFF"
font = "monospace"
